export type PipelineOperator =
  '$abs'
  | '$accumulator'
  | '$acos'
  | '$acosh'
  | '$add'
  | '$addToSet'
  | '$allElementsTrue'
  | '$and'
  | '$anyElementTrue'
  | '$arrayElemAt'
  | '$arrayToObject'
  | '$asin'
  | '$asinh'
  | '$atan'
  | '$atan2'
  | '$atanh'
  | '$avg'
  | '$binarySize'
  | '$bitAnd'
  | '$bitNot'
  | '$bitOr'
  | '$bitXor'
  | '$bsonSize'
  | '$ceil'
  | '$cmp'
  | '$concat'
  | '$concatArrays'
  | '$cond'
  | '$convert'
  | '$cos'
  | '$cosh'
  | '$dateFromParts'
  | '$dateFromString'
  | '$dateToParts'
  | '$dateToString'
  | '$dayOfMonth'
  | '$dayOfWeek'
  | '$dayOfYear'
  | '$degreesToRadians'
  | '$denseRank'
  | '$derivative'
  | '$divide'
  | '$documentNumber'
  | '$eq'
  | '$exp'
  | '$expMovingAvg'
  | '$filter'
  | '$first'
  | '$firstN'
  | '$floor'
  | '$function'
  | '$getField'
  | '$gt'
  | '$gte'
  | '$hour'
  | '$ifNull'
  | '$in'
  | '$indexOfArray'
  | '$indexOfBytes'
  | '$indexOfCP'
  | '$integral'
  | '$isArray'
  | '$isNumber'
  | '$isoDayOfWeek'
  | '$isoWeek'
  | '$isoWeekYear'
  | '$last'
  | '$lastN'
  | '$let'
  | '$linearFill'
  | '$literal'
  | '$ln'
  | '$locf'
  | '$log'
  | '$log10'
  | '$lt'
  | '$lte'
  | '$ltrim'
  | '$map'
  | '$max'
  | '$maxN'
  | '$median'
  | '$mergeObjects'
  | '$meta'
  | '$millisecond'
  | '$min'
  | '$minN'
  | '$minute'
  | '$mod'
  | '$month'
  | '$multiply'
  | '$ne'
  | '$not'
  | '$objectToArray'
  | '$or'
  | '$percentile'
  | '$pow'
  | '$push'
  | '$rank'
  | '$shift'
  | '$sortArray'
  | '$top'
  | '$topN'
  | '$radiansToDegrees'
  | '$rand'
  | '$range'
  | '$reduce'
  | '$regexFind'
  | '$regexFindAll'
  | '$regexMatch'
  | '$replaceOne'
  | '$replaceAll'
  | '$reverseArray'
  | '$round'
  | '$rtrim'
  | '$second'
  | '$setDifference'
  | '$setEquals'
  | '$setField'
  | '$setIntersection'
  | '$setIsSubset'
  | '$setUnion'
  | '$sin'
  | '$sinh'
  | '$size'
  | '$slice'
  | '$split'
  | '$sqrt'
  | '$stdDevPop'
  | '$stdDevSamp'
  | '$strLenBytes'
  | '$strLenCP'
  | '$strcasecmp'
  | '$substr'
  | '$substrBytes'
  | '$substrCP'
  | '$subtract'
  | '$sum'
  | '$switch'
  | '$tan'
  | '$tanh'
  | '$toBool'
  | '$toDate'
  | '$toDecimal'
  | '$toDouble'
  | '$toInt'
  | '$toLong'
  | '$toLower'
  | '$toObjectId'
  | '$toString'
  | '$toUpper'
  | '$trim'
  | '$trunc'
  | '$tsIncrement'
  | '$tsSecond'
  | '$type'
  | '$unsetField'
  | '$week'
  | '$year'
  | '$zip';

export type OperatorExpression = {
  $abs?: any;
  $accumulator?: any;
  $acos?: any;
  $acosh?: any;
  $add?: any;
  $addToSet?: any;
  $allElementsTrue?: any;
  $and?: any;
  $anyElementTrue?: any;
  $arrayElemAt?: any;
  $arrayToObject?: any;
  $asin?: any;
  $asinh?: any;
  $atan?: any;
  $atan2?: any;
  $atanh?: any;
  $avg?: any;
  $binarySize?: any;
  $bitAnd?: any;
  $bitNot?: any;
  $bitOr?: any;
  $bitXor?: any;
  $bsonSize?: any;
  $ceil?: any;
  $cmp?: any;
  $concat?: any;
  $concatArrays?: any;
  $cond?: any;
  $convert?: any;
  $cos?: any;
  $cosh?: any;
  $dateFromParts?: any;
  $dateFromString?: any;
  $dateToParts?: any;
  $dateToString?: any;
  $dayOfMonth?: any;
  $dayOfWeek?: any;
  $dayOfYear?: any;
  $degreesToRadians?: any;
  $denseRank?: any;
  $derivative?: any;
  $divide?: any;
  $documentNumber?: any;
  $eq?: any;
  $exp?: any;
  $expMovingAvg?: any;
  $filter?: any;
  $first?: any;
  $firstN?: any;
  $floor?: any;
  $function?: any;
  $getField?: any;
  $gt?: any;
  $gte?: any;
  $hour?: any;
  $ifNull?: any;
  $in?: any;
  $indexOfArray?: any;
  $indexOfBytes?: any;
  $indexOfCP?: any;
  $integral?: any;
  $isArray?: any;
  $isNumber?: any;
  $isoDayOfWeek?: any;
  $isoWeek?: any;
  $isoWeekYear?: any;
  $last?: any;
  $lastN?: any;
  $let?: any;
  $linearFill?: any;
  $literal?: any;
  $ln?: any;
  $locf?: any;
  $log?: any;
  $log10?: any;
  $lt?: any;
  $lte?: any;
  $ltrim?: any;
  $map?: any;
  $max?: any;
  $maxN?: any;
  $median?: any;
  $mergeObjects?: any;
  $meta?: any;
  $millisecond?: any;
  $min?: any;
  $minN?: any;
  $minute?: any;
  $mod?: any;
  $month?: any;
  $multiply?: any;
  $ne?: any;
  $not?: any;
  $objectToArray?: any;
  $or?: any;
  $percentile?: any;
  $pow?: any;
  $push?: any;
  $radiansToDegrees?: any;
  $rand?: any;
  $range?: any;
  $rank?: any;
  $reduce?: any;
  $regexFind?: any;
  $regexFindAll?: any;
  $regexMatch?: any;
  $replaceOne?: any;
  $replaceAll?: any;
  $reverseArray?: any;
  $round?: any;
  $rtrim?: any;
  $second?: any;
  $setDifference?: any;
  $setEquals?: any;
  $setField?: any;
  $setIntersection?: any;
  $setIsSubset?: any;
  $setUnion?: any;
  $shift?: any;
  $sin?: any;
  $sinh?: any;
  $size?: any;
  $slice?: any;
  $sortArray?: any;
  $split?: any;
  $sqrt?: any;
  $stdDevPop?: any;
  $stdDevSamp?: any;
  $strLenBytes?: any;
  $strLenCP?: any;
  $strcasecmp?: any;
  $substr?: any;
  $substrBytes?: any;
  $substrCP?: any;
  $subtract?: any;
  $sum?: any;
  $tsIncrement?: any;
  $tsSecond?: any;
  $unsetField?: any;
   $switch?: any;
   $tan?: any;
   $tanh?: any;
   $toBool?: any;
   $toDate?: any;
   $toDecimal?: any;
   $toDouble?: any;
   $toInt?: any;
   $toLong?: any;
   $toLower?: any;
   $toObjectId?: any;
   $toString?: any;
   $toUpper?: any;
   $top?: any;
   $topN?: any;
   $trim?: any;
   $trunc?: any;
   $type?: any;
   $week?: any;
   $year?: any;
   $zip?: any;
};

