import {
    addFieldsPayloadValidator,
    bucketAutoPayloadValidator,
    bucketPayloadValidator,
    collStatsPayloadValidator,
    countPayloadValidator,
    facetPayloadValidator,
    geoNearPayloadValidator,
    graphLookupPayloadValidator,
    groupPayloadValidator,
    indexStatsPayloadValidator,
    limitPayloadValidator,
    listSessionsPayloadValidator,
    lookupPayloadValidator,
    matchPayloadValidator,
    mergePayloadValidator,
    outPayloadValidator,
    planCacheStatsPayloadValidator,
    projectPayloadValidator,
    redactPayloadValidator,
    replaceRootPayloadValidator,
    replaceWithPayloadValidator,
    samplePayloadValidator,
    searchPayloadValidator,
    setPayloadValidator,
    skipPayloadValidator,
    sortByCountPayloadValidator,
    sortPayloadValidator,
    unionWithPayloadValidator,
    unsetPayloadValidator,
    unwindPayloadValidator
} from "../validators";

/**
 * Contains the list of all stage validators.
 */
export const PAYLOAD_VALIDATION_ENABLED: { [key: string]: any } = {
    addFields: addFieldsPayloadValidator,
    bucket: bucketPayloadValidator,
    bucketAuto: bucketAutoPayloadValidator,
    collStats: collStatsPayloadValidator,
    count: countPayloadValidator,
    facet: facetPayloadValidator,
    geoNear: geoNearPayloadValidator,
    graphLookup: graphLookupPayloadValidator,
    group: groupPayloadValidator,
    indexStats: indexStatsPayloadValidator,
    limit: limitPayloadValidator,
    listSessions: listSessionsPayloadValidator,
    lookup: lookupPayloadValidator,
    match: matchPayloadValidator,
    merge: mergePayloadValidator,
    out: outPayloadValidator,
    planCacheStats: planCacheStatsPayloadValidator,
    project: projectPayloadValidator,
    redact: redactPayloadValidator,
    replaceRoot: replaceRootPayloadValidator,
    replaceWith: replaceWithPayloadValidator,
    sample: samplePayloadValidator,
    search: searchPayloadValidator,
    set: setPayloadValidator,
    skip: skipPayloadValidator,
    sort: sortPayloadValidator,
    sortByCount: sortByCountPayloadValidator,
    unionWith: unionWithPayloadValidator,
    unset: unsetPayloadValidator,
    unwind: unwindPayloadValidator
}
