import { CountOptions, FacetSearch, HighlightOptions, SearchOperator, TrackingOptions } from '../shared';
import { SortStage } from './sort-stage';

export type SearchStageFields = {
  /**
   * Parallelize search across segments on dedicated search nodes. If you don't have separate search nodes on your
   * cluster, Atlas Search ignores this flag. If omitted, defaults to false. To learn more, see Parallelize Query
   * Execution Across Segments.
   */
  concurrent?: boolean;
  /**
   * Document that specifies the count options for retrieving a count of the results. To learn more, see Count Atlas
   * Search Results.
   */
  count?: CountOptions;
  highlight?: HighlightOptions;
  /**
   * Name of the Atlas Search index to use. If omitted, defaults to default.
   *
   * Note
   * If you name your index default, you don't need to specify an index parameter when using the $search pipeline stage.
   * Otherwise, you must specify the index name using the index parameter.
   *
   * Atlas Search doesn't returns results if you misspell the index name or if the specified index doesn't already exist
   * on the cluster.
   */
  index?: string;
  /**
   * Flag that specifies whether to perform a full document lookup on the backend database or return only stored source
   * fields directly from Atlas Search. If omitted, defaults to false. To learn more, see Return Stored Source Fields.
   */
  returnStoredSource?: boolean;
  /**
   * Reference point for retrieving results. searchAfter returns documents starting immediately following the specified
   * reference point. The reference point must be a Base64-encoded token generated by the $meta keyword
   * searchSequenceToken. To learn more, see Paginate the Results. This field is mutually exclusive with the
   * searchBefore field.
   */
  searchAfter?: string;
  /**
   * Reference point for retrieving results. searchBefore returns documents starting immediately before the specified
   * reference point. The reference point must be a Base64-encoded token generated by the $meta keyword
   * searchSequenceToken. To learn more, see Paginate the Results. This field is mutually exclusive with the
   * searchAfter field.
   */
  searchBefore?: string;
  /**
   * Flag that specifies whether to retrieve a detailed breakdown of the score for the documents in the results. If
   * omitted, defaults to false. To view the details, you must use the $meta expression in the $project stage. To learn
   * more, see Return the Score Details.
   */
  scoreDetails?: boolean;
  /**
   * Document that specifies the fields to sort the Atlas Search results by in ascending or descending order. You can
   * sort by date, number (integer, float, and double values), and string values. To learn more, see Sort Atlas Search
   * Results.
   */
  sort?: SortStage;
  /**
   * Document that specifies the tracking option to retrieve analytics information on the search terms.
   */
  tracking?: TrackingOptions;
};

export type SearchStageOperators = (FacetSearch | SearchOperator);

/**
 * The $search stage performs a full-text search on the specified field or fields. The field or fields must be covered
 * by an Atlas Search index.
 */
export type SearchStage = SearchStageFields & SearchStageOperators;